### ISSUE TITLE
Issue in Version 4.2.4

### ISSUE THREAD

**Issue by Vinodonly** [angular-ui/ui-grid#6576]
It seems the newer version is having refresh issue.. I'm using bootstrap tabcontrol , when we move from one tab to another then instead of displaying grid it shows a grey box.. 

pls see attached snapshot also..

Pls let me know if more details are needed
![grid_issue](https://user-images.githubusercontent.com/16813245/36340531-fbd8ba14-1404-11e8-972d-dfdecbd038de.png)

**Comment by mportuga** [comment]
Could you please provide a plunker with this issue?

**Comment by rosariosanto** [comment]
I recently upgraded to uigrid version 4.2.4 and I started having a similar issue. In my case when switching between two tabs (both of them have a grid with many columns), only the first 4 or five columns display. As soon as you click or select a row from grid, the other columns display.  The fix this issue added code to refresh/resize the grid using the timeout method.

            $timeout(function () {
                $scope.piqGridApi.core.refresh();
                $scope.piqGridApi.grid.handleWindowResize();
            });

**Comment by mportuga** [comment]
Based on the information provided, this is definitely a digest cycle issue. It needs some investigation before a proper solution can be found. A plunker of the issuer would still be helpful however.

**Comment by Blindsyde** [comment]
I am having a similar issue, but mine also does something where all the columns are smashed to the left of grid and the columns are what appears to be the minimum allow width. I tried what rosariosanto suggested and it fixed my issue.
![columssmashedleft](https://user-images.githubusercontent.com/8527885/39069580-6f2e9358-449d-11e8-8662-a070fd4dfe76.JPG)

**Comment by mportuga** [comment]
Yet again, if someone can provide a plunker, that will help with debugging.

**Comment by Blindsyde** [comment]
I am working on it, out of all the grids on my page only one was having the issue, not much difference between them, I'll see if I can reproduce.

**Comment by Blindsyde** [comment]
Looks like I reproduced it, just click the view orders button.
https://jsfiddle.net/Blindsyde/uogqg1j2/

**Comment by sharkysan** [comment]
I have the similar issue after the update. Looks like the "ui-grid-auto-resize" has now a timing issue in case the grid is hidden on page load (as described in http://ui-grid.info/docs/#!/tutorial/108_hidden_grids)
Simple case: http://plnkr.co/edit/x2n6jVUkGtGo1XEJvnUa to reproduce.

**Comment by mportuga** [comment]
I believe this is the commit that introduced the issue:
https://github.com/angular-ui/ui-grid/commit/835153ce256fbeb5f58e20752ca7a4ea35b7a963

**Comment by aaradi** [comment]
@Blindsyde - this is a common issue. You should never use ng-show / ng-hide to show / hide the grid. Use only ng-if.

**Comment by Blindsyde** [comment]
@aardi Using ng-if worked, however the ng-hide worked before the last release too. Either way I fixed my issue by adding 
` $timeout(function () {
            $scope.piqGridApi.core.refresh();
            $scope.piqGridApi.grid.handleWindowResize();
        });         `

**Comment by aaradi** [comment]
@Blindsyde Full documentation about hiding / showing grids: http://ui-grid.info/docs/#!/tutorial/108_hidden_grids

**Comment by Blindsyde** [comment]
@aaradi Thank you

**Comment by peirceb** [comment]
Had a similar issue. My fix was using visibility:hidden in place of ng-hide.

**Comment by lmame** [comment]
So it seems the problem is still there with ng-hide and latest version (4.6.3).
Are there plans to solve this at some point?

The documentation in http://ui-grid.info/docs/#!/tutorial/Tutorial:%20108%20Hidden%20Grids mentions that one of the solution is to use autoResize though this solution does not work.

I made a simple plunkr here that shows the behavior with ng-hide (does not work), ng-if (works but for some reasons we do not really want to go this path as we have some kind of canvas and could have multiple embedded containers that could be hidden) and setting visibility directly (works) but which is a hack. I am using auto-resize but that does not solve the problem with ng-hide.
http://plnkr.co/edit/4BVSlnwIxCZmjDpm0E4D?p=preview
Uncomment the right div to test each case and see.

**Comment by orneryd** [comment]
Thanks for contributing! This repository has been transferred, and we're preparing the new 5.x release. We're closing older issues and pull requests as part of the reset. Please join us on Discord to follow the work or continue the conversation: https://discord.gg/Baz4w8ZWN
