### ISSUE TITLE
Grid:Export to Excel stopped working

### ISSUE THREAD

**Issue by paradizex** [angular-ui/ui-grid#6774]
I was trying to Export my grid data to Excel after Deploying throught my Jenkins CI today and it wouldn't export. On further investigation I found that even the sample grid on UI-Grid's wesite is throwing the same error

Link: http://ui-grid.info/docs/#!/tutorial/206_exporting_data
Error:
```
TypeError: docDefinition is null
Stack trace:
formatAsExcel@http://ui-grid.info/release/ui-grid.js:20694:17
excelExport/<@http://ui-grid.info/release/ui-grid.js:20809:32
processQueue@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:17374:37
scheduleProcessQueue/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:17422:27
$digest@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:18535:15
$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:18923:13
ngEventHandler/<@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:28069:17
defaultHandlerWrapper@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:3780:3
eventHandler@http://ajax.googleapis.com/ajax/libs/angularjs/1.7.0/angular.js:3768:9

```
I have tried to use both Chrome & Firefox, but Excel Export does not work.

**Edit 1:** screenshot

![image](https://user-images.githubusercontent.com/14075276/41836882-58bba134-789f-11e8-987d-b4f030ddb3be.png)

**Edit 2:** The last version it works for me is on bower v4.4.7

**Comment by sujeetpillai** [comment]
I found the issue in exporterExcelCustomFormatter. That was causing the error for me. I fixed the wrong function the first time. I've sent an additional commit to the pull request.

**Comment by Kirti-Chandra-Shahi** [comment]
UI-grid export feature is Not working on a deployment. But for a different server with older deployment it works fine. We aren't getting any error.
We copied the published folder from older deployment & deployed it in our test server. But it didn't resolve the issue. Everything else works fine, but not the export feature.
